title: Reason Studio remote scripts for Arturia Keylab Essential
# description: [A short description of your site's purpose]
locale: en_US
theme: jekyll-theme-cayman
show_downloads: "true" 
google_analytics: G-8X8HC2WZR9
plugins:
  - jemoji
  